base:
  config:
    - "./evaluation/radchest.yaml"
    - "./evaluation/baselines/segresencoder_ctfm.yaml"
  vars#name: "ctfm" # This will be suffixed with a unique ID for the trial
  vars#project: "radchest_hyperparam_search"
  vars#wandb_group: "param_search"
  trainer#strategy: "auto"
  vars#embedding_dim: 512

hyperparams:
  storage: "sqlite:///db.sqlite3"
  n_trials: 50
  pruning: True
  monitor: "val/metrics/MultilabelAUROC/epoch"
  direction: maximize
  system#optimizer#lr:
    type: "float"
    range: [0.00001, 0.001]
    log: True
  system#optimizer#weight_decay:
    type: "float"
    range: [0.00001, 0.05]
    log: True
  system#scheduler#warmup_steps:
    type: "int"
    range: [1, 10]
  vars#pool_size:
    type: "categorical"
    choices: [1, 2]
  