0:
  params:
  - model.head.8.bias
  - model.head.8.weight
  - model.head.5.bias
  - model.head.5.weight
  - model.head.2.bias
  - model.head.2.weight  
  - model.trunk.layers.4.blocks.3.norm2.bias
  - model.trunk.layers.4.blocks.3.norm2.weight
  - model.trunk.layers.4.blocks.3.norm1.bias
  - model.trunk.layers.4.blocks.3.norm1.weight
  - model.trunk.layers.4.blocks.2.norm2.bias
  - model.trunk.layers.4.blocks.2.norm2.weight
  - model.trunk.layers.4.blocks.2.norm1.bias
  - model.trunk.layers.4.blocks.2.norm1.weight
  - model.trunk.layers.4.blocks.1.norm2.bias
  - model.trunk.layers.4.blocks.1.norm2.weight
  - model.trunk.layers.4.blocks.1.norm1.bias
  - model.trunk.layers.4.blocks.1.norm1.weight
  - model.trunk.layers.4.blocks.0.norm2.bias
  - model.trunk.layers.4.blocks.0.norm2.weight
  - model.trunk.layers.4.blocks.0.norm1.bias
  - model.trunk.layers.4.blocks.0.norm1.weight
  - model.trunk.layers.3.blocks.3.norm2.bias
  - model.trunk.layers.3.blocks.3.norm2.weight
  - model.trunk.layers.3.blocks.3.norm1.bias
  - model.trunk.layers.3.blocks.3.norm1.weight
  - model.trunk.layers.3.blocks.2.norm2.bias
  - model.trunk.layers.3.blocks.2.norm2.weight
  - model.trunk.layers.3.blocks.2.norm1.bias
  - model.trunk.layers.3.blocks.2.norm1.weight
  - model.trunk.layers.3.blocks.1.norm2.bias
  - model.trunk.layers.3.blocks.1.norm2.weight
  - model.trunk.layers.3.blocks.1.norm1.bias
  - model.trunk.layers.3.blocks.1.norm1.weight
  - model.trunk.layers.3.blocks.0.norm2.bias
  - model.trunk.layers.3.blocks.0.norm2.weight
  - model.trunk.layers.3.blocks.0.norm1.bias
  - model.trunk.layers.3.blocks.0.norm1.weight
  - model.trunk.layers.2.blocks.1.norm2.bias
  - model.trunk.layers.2.blocks.1.norm2.weight
  - model.trunk.layers.2.blocks.1.norm1.bias
  - model.trunk.layers.2.blocks.1.norm1.weight
  - model.trunk.layers.2.blocks.0.norm2.bias
  - model.trunk.layers.2.blocks.0.norm2.weight
  - model.trunk.layers.2.blocks.0.norm1.bias
  - model.trunk.layers.2.blocks.0.norm1.weight
  - model.trunk.layers.1.blocks.1.norm2.bias
  - model.trunk.layers.1.blocks.1.norm2.weight
  - model.trunk.layers.1.blocks.1.norm1.bias
  - model.trunk.layers.1.blocks.1.norm1.weight
  - model.trunk.layers.1.blocks.0.norm2.bias
  - model.trunk.layers.1.blocks.0.norm2.weight
  - model.trunk.layers.1.blocks.0.norm1.bias
  - model.trunk.layers.1.blocks.0.norm1.weight
  - model.trunk.layers.0.blocks.0.norm2.bias
  - model.trunk.layers.0.blocks.0.norm2.weight
  - model.trunk.layers.0.blocks.0.norm1.bias
  - model.trunk.layers.0.blocks.0.norm1.weight
1:
  params:
  - model.trunk.layers.4.blocks.3.conv2.weight
  - model.trunk.layers.4.blocks.3.conv1.weight
2:
  params:
  - model.trunk.layers.4.blocks.2.conv2.weight
  - model.trunk.layers.4.blocks.2.conv1.weight
3:
  params:
  - model.trunk.layers.4.blocks.1.conv2.weight
  - model.trunk.layers.4.blocks.1.conv1.weight
4:
  params:
  - model.trunk.layers.4.blocks.0.conv2.weight
  - model.trunk.layers.4.blocks.0.conv1.weight
5:
  params:
  - model.trunk.layers.3.downsample.weight
  - model.trunk.layers.3.blocks.3.conv2.weight
  - model.trunk.layers.3.blocks.3.conv1.weight
6:
  params:
  - model.trunk.layers.3.blocks.2.conv2.weight
  - model.trunk.layers.3.blocks.2.conv1.weight
7:
  params:
  - model.trunk.layers.3.blocks.1.conv2.weight
  - model.trunk.layers.3.blocks.1.conv1.weight
8:
  params:
  - model.trunk.layers.3.blocks.0.conv2.weight
  - model.trunk.layers.3.blocks.0.conv1.weight
9:
  params:
  - model.trunk.layers.2.downsample.weight
  - model.trunk.layers.2.blocks.1.conv2.weight
  - model.trunk.layers.2.blocks.1.conv1.weight
10:
  params:
  - model.trunk.layers.2.blocks.0.conv2.weight
  - model.trunk.layers.2.blocks.0.conv1.weight
11:
  params:
  - model.trunk.layers.1.downsample.weight
  - model.trunk.layers.1.blocks.1.conv2.weight
12:
  params:
  - model.trunk.layers.1.blocks.1.conv1.weight
  - model.trunk.layers.1.blocks.0.conv2.weight
13:
  params:
  - model.trunk.layers.1.blocks.0.conv1.weight
  - model.trunk.layers.0.downsample.weight
  - model.trunk.layers.0.blocks.0.conv2.weight
14:
  params:
  - model.trunk.layers.0.blocks.0.conv1.weight
  - model.trunk.conv_init.weight
