vars#name: random_init_eval
system#model#trunk:
    _target_: monai.networks.nets.segresnet_ds.SegResEncoder
    spatial_dims: 3
    in_channels: "@vars#in_channels"
    init_filters: 32
    blocks_down: [1, 2, 2, 4, 4]

trainer#callbacks: null