vars#embedding_dim: 768
vars#axcodes: "RAS"
system#model#trunk:
      _target_: lighter.utils.model.adjust_prefix_and_load_state_dict
      ckpt_path: "/mnt/data1/CT_FM/baselines/VISTA3D/vista3d/models/model.pt"
      ckpt_to_model_prefix: '${"image_encoder.encoder" : ""}'
      model:
        _target_: monai.networks.nets.segresnet_ds.SegResEncoder
        spatial_dims: 3
        in_channels: "@vars#in_channels"
        init_filters: 48
        blocks_down: [1, 2, 2, 4, 4]
        norm: "instance"