vars#embedding_dim: 128
vars#axcodes: "RAS"

# trainer#strategy: ddp_find_unused_parameters_true

system#model#model#trunk:
      _target_: project.models.suprem.SuPreM_loader
      model:
        _target_: monai.networks.nets.SegResNet
        in_channels: "%vars#in_channels"
        out_channels: "%vars#num_classes"
        init_filters: 16
        dropout_prob: 0.0
        blocks_down: [1, 2, 2, 4]
        blocks_up: [1, 1, 1]
      ckpt_path: "/mnt/data1/CT_FM/baselines/SuPreM_SegResNet/supervised_suprem_segresnet_2100.pth"
      decoder: False
      encoder_only: True

system#model#model#pre_func: null