CONSTANTS#name: suprem_unet_eval
CONSTANTS#embedding_dim: 512
system#model#model#trunk:
      _target_: project.models.suprem.SuPreM_loader
      model:
        _target_: project.models.backbones.unet3d.UNet3D
        n_class: "%CONSTANTS#num_classes"
      ckpt_path: "/mnt/data1/CT_FM/baselines/SuPreM_UNet/supervised_suprem_unet_2100.pth"
      decoder: False
      encoder_only: True


system#model#model#pre_func: null
