project: .
_requires_:
    - "$import monai"
    - "$import torch"

args:
  validate:
    ckpt_path: $f"{@vars#save_dir}/best.ckpt"
  test: "%#validate"
  predict: "%#validate"

vars:
    init_LR: 0.0002
    patch_size: "$[144, 192, 192] if @vars#format == 'lighter' else [160, 160, 144]"
    spacing: "$[3, 1, 1] if @vars#format == 'lighter' else [1, 1, 3]"
    axcodes: "$'SPL' if @vars#format == 'lighter' else 'RAS'"
    in_channels: 1
    out_channels: 17
    samples: null
    class_labels:
      _target_: project.data.get_word_class_labels
    # Percentage of the dataset to use
    intensity_range: [-963, 1053]
    # System specific variables
    dataset_dir: "/mnt/data1/datasets/WORD-V0.1.0"
    cache_dir: '$f"/mnt/data1/suraj/lighter_cache/{@vars#project}/{@vars#format}/{@vars#name}"'
    format: "$'monai' if 'suprem' in @vars#name or 'vista' in @vars#name else 'lighter'"
    save_dir: '$f"/mnt/data1/CT_FM/evaluations/{@vars#project}/checkpoints/{@vars#name}_{@vars#wandb_group}"'

trainer:
    _target_: pytorch_lightning.Trainer
    benchmark: True
    max_epochs: 300
    check_val_every_n_epoch: 5
    accelerator: gpu
    # ---------
    devices: 1
    # strategy: ddp
    # sync_batchnorm: True
    # ---------
    precision: 16-mixed
    log_every_n_steps: 5
    logger:
        _target_: pytorch_lightning.loggers.WandbLogger
        project: "@vars#project"
        name: "@vars#name"
        save_dir:  "$@vars#save_dir.replace('checkpoints', 'logs')"
        group: "@vars#wandb_group"

    callbacks:
        - _target_: lighter.callbacks.LighterFreezer
          name_starts_with: ["trunk.encoder"]

        - _target_: pytorch_lightning.callbacks.ModelCheckpoint
          dirpath: "@vars#save_dir"
          save_last: False
          monitor: "val/metrics/Macro_Dice/epoch"
          mode: "max"
          filename: "best"
          auto_insert_metric_name: False
          verbose: True
          every_n_epochs: 5

        - _target_: project.callbacks.WandbImageLogger

system:
    _target_: lighter.LighterSystem
    batch_size: 4
    pin_memory: True
    num_workers: 8
    model:
        _target_: project.models.wrapper.TrunkHeadWrapper
        trunk:
          _target_: lighter.utils.model.adjust_prefix_and_load_state_dict
          ckpt_path: 
          # ckpt_to_model_prefix: '${"_orig_mod.backbone.encoder" : "encoder"} if "recon" in @vars#name else {"_orig_mod.backbone.": "encoder"}'
          ckpt_to_model_prefix: '${"backbone.encoder" : "encoder"} if "recon" in @vars#name else {"backbone.": "encoder"}'
          model:
            _target_: monai.networks.nets.SegResNetDS
            spatial_dims: 3
            in_channels: "@vars#in_channels"
            out_channels: "@vars#out_channels"
            init_filters: 32
            blocks_down: [1, 2, 2, 4, 4]
            dsdepth: 4
        head: null

    criterion:
        _target_: monai.losses.DeepSupervisionLoss
        loss:
          _target_: monai.losses.DiceCELoss
          softmax: True
          to_onehot_y: True
          include_background: True
          squared_pred: True
          smooth_nr: 0
          smooth_dr: 1.0e-05

    optimizer:
        _target_: torch.optim.AdamW
        params: "$@system#model.parameters()"
        lr: "@vars#init_LR"
        weight_decay: 1.0e-05 

    scheduler:
        _target_: monai.optimizers.WarmupCosineSchedule
        optimizer: "@system#optimizer"
        warmup_steps: "$@trainer#max_epochs/100"
        end_lr:  "$@system#optimizer#lr * 0.01"
        warmup_multiplier: 0.1
        t_total: "@trainer#max_epochs"

    metrics:
        train:
          # Classwise_Dice:
          #     _target_: torchmetrics.wrappers.ClasswiseWrapper
          #     metric:
          #       _target_: project.metrics.monai.DiceScore
          #       include_background: True
          #       per_class: True
          #     labels: "@vars#class_labels"
          Macro_Dice:
              _target_: project.metrics.monai.DiceScore
              include_background: False
              per_class: False
          Dice:
              _target_: torchmetrics.Dice
              compute_on_cpu: True
              compute_with_cache: False
              ignore_index: 0
              num_classes: "@vars#out_channels"
              
        val: "%#train"

    datasets:
        train:
            _target_: monai.data.PersistentDataset
            cache_dir: '$f"{@vars#cache_dir}/train"'
            hash_transform: "$monai.data.utils.json_hashing"
            data:
                _target_: project.data.get_word_datalist
                data_dir: "@vars#dataset_dir"
                split: "train"
                samples: "@vars#samples"
            transform:
                _target_: monai.transforms.Compose
                map_items: False
                transforms: 
                    - _target_: monai.transforms.LoadImaged
                      reader: "ITKReader"
                      keys: ["image", "label"]
                      ensure_channel_first: True
                    - _target_: monai.transforms.EnsureTyped
                      keys: ["image", "label"]
                    - _target_: monai.transforms.Orientationd
                      keys: ["image", "label"]
                      axcodes: "@vars#axcodes"
                    - _target_: monai.transforms.Spacingd
                      keys: ["image", "label"]
                      pixdim: "@vars#spacing"
                      mode: ["bilinear", "nearest"]                      
                    - _target_: monai.transforms.ScaleIntensityRanged
                      keys: image
                      a_min: "$@vars#intensity_range[0]"
                      a_max: "$@vars#intensity_range[1]"
                      b_min: 0
                      b_max: 1
                      clip: True
                    - _target_: monai.transforms.CropForegroundd
                      keys: ["image", "label"]
                      source_key: image
                      margin: 10
                    - _target_: monai.transforms.SpatialPadd
                      keys: ["image", "label"]
                      spatial_size: "@vars#patch_size"
                      mode: constant
                    - _target_: monai.transforms.RandCropByLabelClassesd # Change this to something with negative sampling
                      keys: ["image", "label"]
                      label_key: "label"
                      image_key: "image"
                      ratios: "$[0] + [1]*(@vars#out_channels-1)"
                      num_classes: "@vars#out_channels"
                      num_samples: 1
                      spatial_size: "@vars#patch_size"   
                      warn: False
                    - _target_: monai.transforms.Lambda
                      func: '$lambda x: x[0]' # Index sample
                      track_meta: False
                    # - _target_: monai.transforms.RandSpatialCropd # Change this to something with negative sampling
                    #   keys: ["image", "label"]
                    #   roi_size: "%vars#patch_size"
                    #   random_size: False                      
                    - _target_: monai.transforms.RandAffined
                      keys: ["image", "label"]
                      mode: ["bilinear", "nearest"]
                      prob: 0.2
                      rotate_range: [0.26, 0.26, 0.26]
                      scale_range: [0.2, 0.2, 0.2]
                      # spatial_size: "@vars#patch_size"
                      cache_grid: True
                      padding_mode: constant
                    - _target_: monai.transforms.RandGaussianSmoothd
                      keys: image
                      prob: 0.2
                      sigma_x: [0.5, 1.0]
                      sigma_y: [0.5, 1.0]
                      sigma_z: [0.5, 1.0]
                    - _target_: monai.transforms.RandScaleIntensityd
                      keys: image
                      factors: 0.3
                      prob: 0.5
                    - _target_: monai.transforms.RandShiftIntensityd
                      keys: image
                      offsets: 0.1
                      prob: 0.5
                    - _target_: monai.transforms.RandGaussianNoised
                      keys: image
                      std: 0.1
                      prob: 0.2
                    - _target_: monai.transforms.Lambda
                      func: '$lambda x: {"input": x["image"].as_tensor(), "target": x["label"].as_tensor(), "id": x["id"]}'
                      track_meta: False
    
        val:
            _target_: monai.data.PersistentDataset
            cache_dir: '$f"{@vars#cache_dir}/val"'
            hash_transform: "$monai.data.utils.json_hashing"
            data:
                _target_: project.data.get_word_datalist
                data_dir: "@vars#dataset_dir"
                split: "val"
                samples: "@vars#samples"
            transform:
                _target_: monai.transforms.Compose
                transforms:
                    - _target_: monai.transforms.LoadImaged
                      keys: ["image", "label"]
                      reader: "ITKReader"
                      ensure_channel_first: True
                    - _target_: monai.transforms.EnsureTyped
                      keys: ["image", "label"]
                    - _target_: monai.transforms.Orientationd
                      keys: ["image", "label"]
                      axcodes: "@vars#axcodes"
                    - _target_: monai.transforms.Spacingd
                      keys: ["image", "label"]
                      pixdim: "@vars#spacing"
                      mode: ["bilinear", "nearest"]                      
                    - _target_: monai.transforms.ScaleIntensityRanged
                      keys: image
                      a_min: "$@vars#intensity_range[0]"
                      a_max: "$@vars#intensity_range[1]"
                      b_min: 0
                      b_max: 1
                      clip: True
                    - _target_: monai.transforms.CropForegroundd
                      keys: ["image", "label"]
                      source_key: image
                      margin: 10
                    # - _target_: monai.transforms.RandSpatialCropd
                    #   keys: ["image", "label"]
                    #   roi_size: "@vars#val_max_patch_size"
                    #   random_size: False
                    - _target_: monai.transforms.Lambda
                      func: '$lambda x: {"input": x["image"].as_tensor(), "target": x["label"].as_tensor(), "id": x["id"]}'
                      track_meta: False

        predict:
            _target_: monai.data.Dataset
            data:
                _target_: project.data.get_word_datalist
                data_dir: "@vars#dataset_dir"
                split: "test"
            transform:
                _target_: monai.transforms.Compose
                transforms:
                    - _target_: monai.transforms.CopyItemsd
                      keys: ["image", "label"]
                      names: ["input", "target",]
                    - _target_: monai.transforms.LoadImaged
                      keys: ["input", "target"]
                      reader: "ITKReader"
                      ensure_channel_first: True
                    - _target_: monai.transforms.EnsureTyped
                      keys: ["input", "target"]
                    - _target_: monai.transforms.Orientationd
                      keys: ["input", "target"]
                      axcodes: "@vars#axcodes"
                    - _target_: monai.transforms.Spacingd
                      keys: ["image", "label"]
                      pixdim: "@vars#spacing"
                      mode: ["bilinear", "nearest"]                      
                    - _target_: monai.transforms.ScaleIntensityRanged
                      keys: input
                      a_min: "$@vars#intensity_range[0]"
                      a_max: "$@vars#intensity_range[1]"
                      b_min: 0
                      b_max: 1
                      clip: True
                    - _target_: monai.transforms.CropForegroundd
                      keys: ["input", "target"]
                      source_key: input
                      margin: 10
                    - _target_: monai.transforms.SelectItemsd
                      keys: ["input", "target", "id"]                      

    postprocessing:
        metrics:
            pred: # Pred for torchmetrics is (N, C, ...)
                # Hacky solution below. DS returns a list when model is in train mode 
                - "$lambda x: x[0] if isinstance(x, list) else x" 
                - "$lambda x: torch.softmax(x, 1)"
            target:
                - "$lambda x: x.squeeze(1).long()"

        logging:              
            pred:
                - "$lambda x: x.argmax(dim=1, keepdim=True)"

            target:
                - "$lambda x: x.unsqueeze(1)"

    inferer:
        _target_: monai.inferers.SlidingWindowInfererAdapt
        roi_size: "@vars#patch_size"
        sw_batch_size: "%system#batch_size"
        overlap: 0.625
        mode: gaussian